### ISSUE TITLE
Large delay between push packets

### ISSUE THREAD

**Issue by jpaw1** [Geontech/FEI_FileReader#1]
During file playback it was observed that boost::this_thread::sleep(timeToWait) was causing a delay of ~13 seconds between packets.

The condition this occurred under was when allocating a single RX_DIGITIZER.

**Comment by patcamwol** [comment]
Hello jpaw1,

Would you mind telling me what other FEI Allocation parameters you were using, particularly the sample rate?

**Comment by jpaw1** [comment]
All settings were default, and the sample rate was 32k with the last part of the file name _32000.I.

**Comment by patcamwol** [comment]
All right, then that's good news. The default number of bytes for a packet is about 90% of the default CORBA MaxTransferSize, or 1887432 bytes. With a sample rate of 32 kSps and a data type of complex short (4 bytes/sample), that comes to 128 kBps. We can then find the time to wait between packets by dividing the bytes per packet by the number of bytes per second, 1887432 / 128000 = 14.75 s. We can then assume that the slight difference between the calculated time and your observed time is from the FEI_FileReader keeping track of how long the pushPacket calls are taking and shortening the wait interval.

So, this is expected behavior for the Device. Is it causing problems in your application?

**Comment by jpaw1** [comment]
This makes perfect sense in regard to this acting like an "actual" FEI device, and I guess I missed that being the intended behavior of this. Would it be possible to extend the functionality of the throttle rate to allow rates greater than the sample rate to enable transfer speeds resembling those of the FileReader component?

**Comment by patcamwol** [comment]
I don't see a problem with that. It would be a useful feature to be able to ramp up your sample rate to your intended "actual" sample rate incrementally for testing purposes.
